import { faker } from "@faker-js/faker";

export const jerseysData = [
  {
    id: "1",
    name: "Camisa Home",
    year: "2023",
    wins: faker.number.int({ min: 5, max: 15 }),
    frequency: faker.number.int({ min: 15, max: 30 }),
    percentage: faker.number.int({ min: 20, max: 100 }),
  },
  {
    id: "2",
    name: "Camisa Away",
    year: "2021",
    wins: faker.number.int({ min: 5, max: 15 }),
    frequency: faker.number.int({ min: 15, max: 30 }),
    percentage: faker.number.int({ min: 20, max: 100 }),
  },
  {
    id: "3",
    name: "Camisa Sócio",
    year: "2021",
    wins: faker.number.int({ min: 5, max: 15 }),
    frequency: faker.number.int({ min: 15, max: 30 }),
    percentage: faker.number.int({ min: 20, max: 100 }),
  },
  {
    id: "4",
    name: "Camisa Alternativa",
    year: "2021",
    wins: faker.number.int({ min: 5, max: 15 }),
    frequency: faker.number.int({ min: 15, max: 30 }),
    percentage: faker.number.int({ min: 20, max: 100 }),
  },
  {
    id: "5",
    name: "Camisa Treino",
    year: "2021",
    wins: faker.number.int({ min: 5, max: 15 }),
    frequency: faker.number.int({ min: 15, max: 30 }),
    percentage: faker.number.int({ min: 20, max: 100 }),
  },
  {
    id: "6",
    name: "Camisa Viagem",
    year: "2021",
    wins: faker.number.int({ min: 5, max: 15 }),
    frequency: faker.number.int({ min: 15, max: 30 }),
    percentage: faker.number.int({ min: 20, max: 100 }),
  },
  {
    id: "7",
    name: "Camisa Away",
    year: "2020",
    wins: faker.number.int({ min: 5, max: 15 }),
    frequency: faker.number.int({ min: 15, max: 30 }),
    percentage: faker.number.int({ min: 20, max: 100 }),
  },
  {
    id: "8",
    name: "Camisa Home",
    year: "2019",
    wins: faker.number.int({ min: 5, max: 15 }),
    frequency: faker.number.int({ min: 15, max: 30 }),
    percentage: faker.number.int({ min: 20, max: 100 }),
  },
  {
    id: "9",
    name: "Camisa Away",
    year: "2021",
    wins: faker.number.int({ min: 5, max: 15 }),
    frequency: faker.number.int({ min: 15, max: 30 }),
    percentage: faker.number.int({ min: 20, max: 100 }),
  },
  {
    id: "10",
    name: "Camisa Home",
    year: "2021",
    wins: faker.number.int({ min: 5, max: 15 }),
    frequency: faker.number.int({ min: 15, max: 30 }),
    percentage: faker.number.int({ min: 20, max: 100 }),
  },
];
