export const stadiumsData = [
  { id: 1, name: "Arena da Baixada", country: "Brasil", city: "Curitiba" },
  { id: 2, name: "Mineirão", country: "Brasil", city: "Belo Horizonte" },
  { id: 3, name: "Antônio Accioly", country: "Brasil", city: "Goiânia" },
  { id: 5, name: "Arena Fonte Nova", country: "Brasil", city: "Salvador" },
  { id: 6, name: "Castelão", country: "Brasil", city: "Fortaleza" },
  { id: 7, name: "Arena Condá", country: "Brasil", city: "Chapecó" },
  { id: 8, name: "Neo Química Arena", country: "Brasil", city: "São Paulo" },
  { id: 9, name: "Couto Pereira", country: "Brasil", city: "Curitiba" },
  { id: 11, name: "Maracanã", country: "Brasil", city: "Rio de Janeiro" },
  { id: 13, name: "Arena do Grêmio", country: "Brasil", city: "Porto Alegre" },
  { id: 14, name: "Beira-Rio", country: "Brasil", city: "Porto Alegre" },
  { id: 15, name: "Allianz Parque", country: "Brasil", city: "São Paulo" },
  {
    id: 16,
    name: "Nabi Abi Chedid",
    country: "Brasil",
    city: "Bragança Paulista",
  },
  { id: 17, name: "Vila Belmiro", country: "Brasil", city: "Santos" },
  { id: 18, name: "Morumbi", country: "Brasil", city: "São Paulo" },
];

export const stadiumsOptions = [
  { id: 1, name: "Mineirão" },
  { id: 2, name: "Arena da Baixada" },
  { id: 3, name: "Estádio Antônio Accioly" },
  { id: 5, name: "Arena Fonte Nova" },
  { id: 6, name: "Castelão" },
  { id: 7, name: "Arena Condá" },
  { id: 8, name: "Neo Química Arena" },
  { id: 9, name: "Estádio Couto Pereira" },
  { id: 11, name: "Maracanã" },
  { id: 13, name: "Arena do Grêmio" },
  { id: 14, name: "Beira-Rio" },
  { id: 15, name: "Allianz Parque" },
  { id: 16, name: "Nabi Abi Chedid" },
  { id: 17, name: "Vila Belmiro" },
  { id: 18, name: "Morumbi" },
  { id: 19, name: "Ilha do Retiro" },
  { id: 20, name: "Ressacada" },
  { id: 21, name: "Santa Cruz" },
  { id: 22, name: "Arena Batistão" },
  { id: 24, name: "Estádio do Café" },
  { id: 25, name: "Estádio dos Aflitos" },
  { id: 26, name: "Estádio Germano Krüger" },
  { id: 27, name: "Estádio Moisés Lucarelli" },
  { id: 29, name: "Estádio Serra Dourada" },
  { id: 30, name: "Brinco de Ouro" },
  { id: 37, name: "São Januário" },
  { id: 38, name: "Estádio da Serrinha" },
  { id: 39, name: "Estádio do Vale" },
  { id: 40, name: "Estádio dos Eucaliptos" },
  { id: 41, name: "Estádio dos Plátanos" },
  { id: 42, name: "La Bombonera" },
  { id: 44, name: "Estadio Libertadores de América" },
  { id: 46, name: "Estadio Pedro Bidegain" },
  { id: 47, name: "Estadio José Amalfitani" },
  { id: 48, name: "Gran Parque Central" },
  { id: 49, name: "Estadio Campeón del Siglo" },
  { id: 50, name: "Estadio Luis Franzini" },
  { id: 51, name: "Arena Corinthians" },
  { id: 52, name: "Allianz Parque" },
  { id: 53, name: "Vila Belmiro" },
  { id: 54, name: "Estádio do Canindé" },
  { id: 55, name: "Estádio Jorge Ismael de Biasi" },
];
