import { faker } from "@faker-js/faker";

export const teamsDashboardData = [
  {
    id: "1",
    name: "Palmeiras",
    wins: faker.number.int({ min: 5, max: 15 }),
    frequency: faker.number.int({ min: 15, max: 30 }),
    percentage: faker.number.int({ min: 50, max: 100 }),
  },
  {
    id: "2",
    name: "Corinthians",
    wins: faker.number.int({ min: 5, max: 15 }),
    frequency: faker.number.int({ min: 15, max: 30 }),
    percentage: faker.number.int({ min: 50, max: 100 }),
  },
  {
    id: "3",
    name: "Santos",
    wins: faker.number.int({ min: 5, max: 15 }),
    frequency: faker.number.int({ min: 15, max: 30 }),
    percentage: faker.number.int({ min: 50, max: 100 }),
  },
  {
    id: "4",
    name: "Santo André",
    wins: faker.number.int({ min: 5, max: 15 }),
    frequency: faker.number.int({ min: 15, max: 30 }),
    percentage: faker.number.int({ min: 50, max: 100 }),
  },
  {
    id: "5",
    name: "Portuguesa",
    wins: faker.number.int({ min: 5, max: 15 }),
    frequency: faker.number.int({ min: 15, max: 30 }),
    percentage: faker.number.int({ min: 50, max: 100 }),
  },
  {
    id: "6",
    name: "Morumbi",
    wins: faker.number.int({ min: 5, max: 15 }),
    frequency: faker.number.int({ min: 15, max: 30 }),
    percentage: faker.number.int({ min: 50, max: 100 }),
  },
  {
    id: "7",
    name: "Morumbi",
    wins: faker.number.int({ min: 5, max: 15 }),
    frequency: faker.number.int({ min: 15, max: 30 }),
    percentage: faker.number.int({ min: 50, max: 100 }),
  },
  {
    id: "8",
    name: "Morumbi",
    wins: faker.number.int({ min: 5, max: 15 }),
    frequency: faker.number.int({ min: 15, max: 30 }),
    percentage: faker.number.int({ min: 50, max: 100 }),
  },
  {
    id: "9",
    name: "Morumbi",
    wins: faker.number.int({ min: 5, max: 15 }),
    frequency: faker.number.int({ min: 15, max: 30 }),
    percentage: faker.number.int({ min: 50, max: 100 }),
  },
  {
    id: "10",
    name: "Morumbi",
    wins: faker.number.int({ min: 5, max: 15 }),
    frequency: faker.number.int({ min: 15, max: 30 }),
    percentage: faker.number.int({ min: 50, max: 100 }),
  },
];

export const teamsData = [
  {
    id: 1,
    name: "América Mineiro",
    country: "Brasil",
    city: "Belo Horizonte",
  },
  {
    id: 2,
    name: "Athletico Paranaense",
    country: "Brasil",
    city: "Curitiba",
  },
  {
    id: 3,
    name: "Atlético Goianiense",
    country: "Brasil",
    city: "Goiânia",
  },
  {
    id: 4,
    name: "Atlético Mineiro",
    country: "Brasil",
    city: "Belo Horizonte",
  },
  {
    id: 5,
    name: "Bahia",
    country: "Brasil",
    city: "Salvador",
  },
  {
    id: 6,
    name: "Ceará",
    country: "Brasil",
    city: "Fortaleza",
  },
  {
    id: 7,
    name: "Chapecoense",
    country: "Brasil",
    city: "Chapecó",
  },
  {
    id: 8,
    name: "Corinthians",
    country: "Brasil",
    city: "São Paulo",
  },
  {
    id: 9,
    name: "Coritiba",
    country: "Brasil",
    city: "Curitiba",
  },
  {
    id: 10,
    name: "Cuiabá",
    country: "Brasil",
    city: "Cuiabá",
  },
  {
    id: 11,
    name: "Flamengo",
    country: "Brasil",
    city: "Rio de Janeiro",
  },
  {
    id: 12,
    name: "Fluminense",
    country: "Brasil",
    city: "Rio de Janeiro",
  },
  {
    id: 13,
    name: "Grêmio",
    country: "Brasil",
    city: "Porto Alegre",
  },
  {
    id: 14,
    name: "Internacional",
    country: "Brasil",
    city: "Porto Alegre",
  },
  {
    id: 15,
    name: "Palmeiras",
    country: "Brasil",
    city: "São Paulo",
  },
  {
    id: 16,
    name: "RB Bragantino",
    country: "Brasil",
    city: "Bragança Paulista",
  },
  {
    id: 17,
    name: "Santos",
    country: "Brasil",
    city: "Santos",
  },
  {
    id: 18,
    name: "São Paulo",
    country: "Brasil",
    city: "São Paulo",
  },
  {
    id: 19,
    name: "Sport Recife",
    country: "Brasil",
    city: "Recife",
  },
  {
    id: 20,
    name: "Avaí",
    country: "Brasil",
    city: "Florianópolis",
  },
  {
    id: 21,
    name: "Botafogo",
    country: "Brasil",
    city: "Ribeirão Preto",
  },
  {
    id: 22,
    name: "Confiança",
    country: "Brasil",
    city: "Aracaju",
  },
  {
    id: 24,
    name: "Londrina",
    country: "Brasil",
    city: "Londrina",
  },
  {
    id: 25,
    name: "Náutico",
    country: "Brasil",
    city: "Recife",
  },
  {
    id: 26,
    name: "Operário Ferroviário",
    country: "Brasil",
    city: "Ponta Grossa",
  },
  {
    id: 27,
    name: "Ponte Preta",
    country: "Brasil",
    city: "Campinas",
  },
  {
    id: 28,
    name: "Remo",
    country: "Brasil",
    city: "Belém",
  },
  {
    id: 29,
    name: "Vila Nova",
    country: "Brasil",
    city: "Goiânia",
  },
  {
    id: 30,
    name: "Guarani",
    country: "Brasil",
    city: "Campinas",
  },
  {
    id: 37,
    name: "Vasco da Gama",
    country: "Brasil",
    city: "Rio de Janeiro",
  },
  {
    id: 38,
    name: "Goiás",
    country: "Brasil",
    city: "Goiânia",
  },
  {
    id: 39,
    name: "Novo Hamburgo",
    country: "Brasil",
    city: "Novo Hamburgo",
  },
  {
    id: 40,
    name: "Pelotas",
    country: "Brasil",
    city: "Pelotas",
  },
  {
    id: 41,
    name: "São José-RS",
    country: "Brasil",
    city: "Porto Alegre",
  },
  {
    id: 42,
    name: "Boca Juniors",
    country: "Argentina",
    city: "Buenos Aires",
  },
  {
    id: 43,
    name: "River Plate",
    country: "Argentina",
    city: "Buenos Aires",
  },
  {
    id: 44,
    name: "Independiente",
    country: "Argentina",
    city: "Avellaneda",
  },
  {
    id: 46,
    name: "San Lorenzo",
    country: "Argentina",
    city: "Buenos Aires",
  },
  {
    id: 47,
    name: "Vélez Sarsfield",
    country: "Argentina",
    city: "Buenos Aires",
  },
  {
    id: 48,
    name: "Nacional",
    country: "Uruguai",
    city: "Montevidéu",
  },
  {
    id: 49,
    name: "Peñarol",
    country: "Uruguai",
    city: "Montevidéu",
  },
  {
    id: 50,
    name: "Defensor Sporting",
    country: "Uruguai",
    city: "Montevidéu",
  },
];

export const teamsOptions = [
  { id: 1, name: "América Mineiro" },
  { id: 2, name: "Athletico Paranaense" },
  { id: 3, name: "Atlético Goianiense" },
  { id: 4, name: "Atlético Mineiro" },
  { id: 5, name: "Bahia" },
  { id: 6, name: "Ceará" },
  { id: 7, name: "Chapecoense" },
  { id: 8, name: "Corinthians" },
  { id: 9, name: "Coritiba" },
  { id: 10, name: "Cuiabá" },
  { id: 11, name: "Flamengo" },
  { id: 12, name: "Fluminense" },
  { id: 13, name: "Grêmio" },
  { id: 14, name: "Internacional" },
  { id: 15, name: "Palmeiras" },
  { id: 16, name: "RB Bragantino" },
  { id: 17, name: "Santos" },
  { id: 18, name: "São Paulo" },
  { id: 19, name: "Sport Recife" },
  { id: 20, name: "Avaí" },
  { id: 21, name: "Botafogo" },
  { id: 22, name: "Confiança" },
  { id: 24, name: "Londrina" },
  { id: 25, name: "Náutico" },
  { id: 26, name: "Operário Ferroviário" },
  { id: 27, name: "Ponte Preta" },
  { id: 28, name: "Remo" },
  { id: 29, name: "Vila Nova" },
  { id: 30, name: "Guarani" },
  { id: 37, name: "Vasco da Gama" },
  { id: 38, name: "Goiás" },
  { id: 39, name: "Novo Hamburgo" },
  { id: 40, name: "Pelotas" },
  { id: 41, name: "São José-RS" },
  { id: 42, name: "Boca Juniors" },
  { id: 43, name: "River Plate" },
  { id: 44, name: "Independiente" },
  { id: 46, name: "San Lorenzo" },
  { id: 47, name: "Vélez Sarsfield" },
  { id: 48, name: "Nacional" },
  { id: 49, name: "Peñarol" },
  { id: 50, name: "Defensor Sporting" },
];
